"""
For each _bak dir generated by dist_qsub, if it does not have a corresponding
non-_bak dir, restore the _bak dir (mv [dname]_bak [dname]).

"""

import os, subprocess

if __name__ == "__main__":
    targ_dir = "."
    dirs = set([name for name in os.listdir(targ_dir) if os.path.isdir(name) and "ntasks_" in name])
    print dirs
    for dname in dirs:
        if "_bak" in dname:
            base = dname.replace("_bak", "")
            if not base in dirs:
                cmd = "mv %s %s" % (dname, base)
                return_code = subprocess.call(cmd, shell = True, cwd = targ_dir)
